---
baseURL: https://babcblog.netlify.app/
languageCode: en-us
timeZone: Africa/Nairobi
title: Bunnie ABC
theme: PaperMod
defaultTheme: auto
googleAnalytics: UA-235280790-1
params:
  homeInfoParams:
    Title: Yowzha!
    Content: Don't memorize I need you back.

    
Params:
  ShowReadingTime: true
  linkFullImages: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  showShareButtons: true
  ShowPostNavLinks: true
  ShowToc: true
  
  # home-info mode
  homeInfoParams:
    Title: "Yowzha"
    Content: "Don't memorize I need you back"

  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/bunniestore.ke/"
    - name: github
      url: "https://github.com/tito-arch"
    - name: linkedin
      url: "https://www.linkedin.com/company/bunnie-abc/"

  editPost:
    URL: "https://github.com/tito-arch/BABC-2/tree/master/content"
    Text: "Edit This Page" # edit text
    appendFilePath: true # to append file path to Edit link
 

menu:
  main:
    - identifier: Apps
      name: App Updates
      url: /categories/app-updates/
      weight: 10
    - identifier: AI
      name: AI & ML
      url: /categories/artificial-intelligence-machine-learning/
      weight: 20
    - identifier: blockchain & Web3
      name: Blockchain & Web3
      url: /categories/blockchain-web3/
      weight: 30
    - identifier: CS
      name: Computer Science
      url: /categories/computer-science/
      weight: 40
    - identifier: Device
      name: Device Reviews
      url: /categories/device-reviews/
      weight: 50
    - identifier: Trending
      name: Tech Trends
      url: /categories/emerging-issues-trends/
      weight: 60     
    - identifier: About
      name: About
      url: /google/about/
      weight: 70  
    - identifier: Privacy policy
      name: Privacy policy
      url: /google/cp/
      weight: 80              
---
